name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            cgo: "1"
            cc: gcc
            name: slack-rotation-bot-linux-amd64
          - goos: linux
            goarch: arm64
            cgo: "1"
            cc: aarch64-linux-gnu-gcc
            name: slack-rotation-bot-linux-arm64
          - goos: darwin
            goarch: amd64
            cgo: "0"
            cc: ""
            name: slack-rotation-bot-darwin-amd64
          - goos: darwin
            goarch: arm64
            cgo: "0"
            cc: ""
            name: slack-rotation-bot-darwin-arm64
          - goos: windows
            goarch: amd64
            cgo: "1"
            cc: x86_64-w64-mingw32-gcc
            name: slack-rotation-bot-windows-amd64.exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install cross-compilation tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu gcc-mingw-w64

      - name: Build binary
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} CGO_ENABLED=${{ matrix.cgo }} CC=${{ matrix.cc }} \
          go build -ldflags="-s -w" -o ${{ matrix.name }} cmd/bot/main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Move binaries to root
        run: |
          find . -name "slack-rotation-bot-*" -type f -exec mv {} . \;

      - name: Create checksums
        run: |
          sha256sum slack-rotation-bot-* > checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.version.outputs.VERSION }}
          body: |
            ## Slack Rotation Bot ${{ steps.version.outputs.VERSION }}
            
            ### 📥 Installation
            
            **Option A: Download Binary**
            1. Download the appropriate binary for your platform below
            2. Make it executable: `chmod +x slack-rotation-bot-*`
            3. Deploy to your server
            
            **Option B: Fork and Build**
            1. Fork this repository to your organization
            2. Build from source following the [DEVELOPMENT.md](https://github.com/diegoclair/slack-rotation-bot/blob/main/DEVELOPMENT.md) guide
            
            ### 🖥️ Platform Support
            - `linux-amd64`: Linux on Intel/AMD processors (with CGO)
            - `linux-arm64`: Linux on ARM processors (with CGO, e.g., AWS Graviton)
            - `darwin-amd64`: macOS on Intel processors (static binary)
            - `darwin-arm64`: macOS on Apple Silicon M1/M2/M3 (static binary)
            - `windows-amd64`: Windows on Intel/AMD processors (with CGO)
            
            ### 🔐 Security
            - Verify downloads using the provided `checksums.txt`
            - All binaries are built with `-ldflags="-s -w"` for optimized size
            - Linux and Windows binaries include CGO for SQLite performance
            - macOS binaries are statically compiled for maximum compatibility
            
            ### 📖 Documentation
            - [README.md](https://github.com/diegoclair/slack-rotation-bot/blob/main/README.md) - Setup and usage guide
            - [DEVELOPMENT.md](https://github.com/diegoclair/slack-rotation-bot/blob/main/DEVELOPMENT.md) - Technical documentation
            
            ### 🚀 Quick Start
            ```bash
            # Linux/macOS
            wget https://github.com/diegoclair/slack-rotation-bot/releases/download/${{ steps.version.outputs.VERSION }}/slack-rotation-bot-linux-amd64
            chmod +x slack-rotation-bot-linux-amd64
            ./slack-rotation-bot-linux-amd64
            ```
            
            Full changelog: https://github.com/diegoclair/slack-rotation-bot/compare/v1.0.0...${{ steps.version.outputs.VERSION }}
          files: |
            slack-rotation-bot-linux-amd64
            slack-rotation-bot-linux-arm64
            slack-rotation-bot-darwin-amd64
            slack-rotation-bot-darwin-arm64
            slack-rotation-bot-windows-amd64.exe
            checksums.txt
          draft: false
          prerelease: false